### ISSUE TITLE
Layout Component

### ISSUE THREAD

**Issue by hackingbeauty** [electrode-io/electrode-react-sample-material-ui#2]
Hi Chip,

I tried to add a Layout component that wraps every individual route, but it doesn't work.

```
 <Route path="/" component={Layout}>
    <IndexRoute component={Home} />
  </Route>
```

Any idea why?

**Comment by jchip** [comment]
I don't think it works that way with react router.  You need to specify a path for each route.  If you want to host React components from multiple routes in a single page like this, you have to implement your container page in a way such that it can retrieve components from different routes and render them into specific container DOM element.

**Comment by santhoshmahalingam** [comment]
Hi Chip,

Thanks for the wonderful material, I am new to react as well electrode your material helps me a lot. But while trying to import images I'm getting error as following, Can you help me on this. 

```
`Register plugins failed { [SyntaxError: D:/electrode/electrodesample/client/images/nature-600-337.jpg: Unexpected character '?' (1:0)]
pos: 0,
loc: Position { line: 1, column: 0 },
_babel: true,
codeFrame: '> 1 | ????\u0000\u0010JFIF\u0000\u0001\u0001\u0001\u0000`\u0000`\u0000\u0000??\u0000;CREATOR: gd-jpeg v1.0 (using IJG JPEG v62), quality = 70\n    |^\n  2 | ??\u0000C\u0000\n  3 | \u0007\u0007\b\u0007\u0006\n  4 | \b\b\b\u000b' }

ESERVERSTART

This error is thrown by the electrode-server module

There was an error starting the Hapi.js server
Please check the output of the stack trace below and correct the error shown

If you have followed this resolution step and you are still seeing an
error, please file an issue on the electrode-server repository

git+https://github.com/electrode-io/electrode-server.git
```

Unhandled rejection SyntaxError: D:/electrode/electrodesample/client/images/nature-600-337.jpg: Unexpected character '?' (1:0)`

Thanks,

**Comment by jchip** [comment]
closing this and keep https://github.com/electrode-io/electrode/issues/129
